extends:
  - eslint:recommended
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: _
      varsIgnorePattern: _
  eqeqeq: error
  prettier/prettier: error
